from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QTextBrowser, QWidget)

class UI_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1020, 745)
        self.actionSave_Network = QAction(MainWindow)
        self.actionSave_Network.setObjectName(u"actionSave_Network")
        self.actionLoad_Network = QAction(MainWindow)
        self.actionLoad_Network.setObjectName(u"actionLoad_Network")
        self.actionNew_Network = QAction(MainWindow)
        self.actionNew_Network.setObjectName(u"actionNew_Network")
        self.actionAdd_Router = QAction(MainWindow)
        self.actionAdd_Router.setObjectName(u"actionAdd_Router")
        self.actionEdit_Router = QAction(MainWindow)
        self.actionEdit_Router.setObjectName(u"actionEdit_Router")
        self.actionDelete_Router = QAction(MainWindow)
        self.actionDelete_Router.setObjectName(u"actionDelete_Router")
        self.actionLink_Routers = QAction(MainWindow)
        self.actionLink_Routers.setObjectName(u"actionLink_Routers")
        self.actionSet_Constraints = QAction(MainWindow)
        self.actionSet_Constraints.setObjectName(u"actionSet_Constraints")
        self.actionFind_Route = QAction(MainWindow)
        self.actionFind_Route.setObjectName(u"actionFind_Route")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(10, 10, 1001, 591))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-3, 600, 1031, 20))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.new_network_button = QPushButton(self.centralwidget)
        self.new_network_button.setObjectName(u"new_network_button")
        self.new_network_button.setGeometry(QRect(10, 620, 111, 28))
        self.save_network_button = QPushButton(self.centralwidget)
        self.save_network_button.setObjectName(u"save_network_button")
        self.save_network_button.setGeometry(QRect(10, 650, 111, 28))
        self.add_router_button = QPushButton(self.centralwidget)
        self.add_router_button.setObjectName(u"add_router_button")
        self.add_router_button.setGeometry(QRect(140, 620, 111, 28))
        self.edit_router_button = QPushButton(self.centralwidget)
        self.edit_router_button.setObjectName(u"edit_router_button")
        self.edit_router_button.setGeometry(QRect(140, 650, 111, 28))
        self.load_network_button = QPushButton(self.centralwidget)
        self.load_network_button.setObjectName(u"load_network_button")
        self.load_network_button.setGeometry(QRect(10, 680, 111, 28))
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(120, 609, 20, 110))
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(250, 610, 20, 110))
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.link_routers_button = QPushButton(self.centralwidget)
        self.link_routers_button.setObjectName(u"link_routers_button")
        self.link_routers_button.setGeometry(QRect(270, 620, 111, 28))
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(380, 610, 20, 110))
        self.line_4.setFrameShape(QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.delete_router_button = QPushButton(self.centralwidget)
        self.delete_router_button.setObjectName(u"delete_router_button")
        self.delete_router_button.setGeometry(QRect(140, 680, 111, 28))
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(400, 619, 610, 91))
        self.set_constraints_button = QPushButton(self.centralwidget)
        self.set_constraints_button.setObjectName(u"set_constraints_button")
        self.set_constraints_button.setGeometry(QRect(270, 650, 111, 28))
        self.find_route_button = QPushButton(self.centralwidget)
        self.find_route_button.setObjectName(u"find_route_button")
        self.find_route_button.setGeometry(QRect(270, 680, 111, 28))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1020, 26))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuRouters = QMenu(self.menubar)
        self.menuRouters.setObjectName(u"menuRouters")
        self.menuSolver = QMenu(self.menubar)
        self.menuSolver.setObjectName(u"menuSolver")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRouters.menuAction())
        self.menubar.addAction(self.menuSolver.menuAction())
        self.menuFile.addAction(self.actionNew_Network)
        self.menuFile.addAction(self.actionSave_Network)
        self.menuFile.addAction(self.actionLoad_Network)
        self.menuRouters.addAction(self.actionAdd_Router)
        self.menuRouters.addAction(self.actionEdit_Router)
        self.menuRouters.addAction(self.actionDelete_Router)
        self.menuRouters.addAction(self.actionLink_Routers)
        self.menuSolver.addAction(self.actionSet_Constraints)
        self.menuSolver.addAction(self.actionFind_Route)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"PyNet Router", None))
        self.actionSave_Network.setText(QCoreApplication.translate("MainWindow", u"Save Network", None))
        self.actionLoad_Network.setText(QCoreApplication.translate("MainWindow", u"Load Network", None))
        self.actionNew_Network.setText(QCoreApplication.translate("MainWindow", u"New Network", None))
        self.actionAdd_Router.setText(QCoreApplication.translate("MainWindow", u"Add Router", None))
        self.actionEdit_Router.setText(QCoreApplication.translate("MainWindow", u"Edit Router", None))
        self.actionDelete_Router.setText(QCoreApplication.translate("MainWindow", u"Delete Router", None))
        self.actionLink_Routers.setText(QCoreApplication.translate("MainWindow", u"Link Routers", None))
        self.actionSet_Constraints.setText(QCoreApplication.translate("MainWindow", u"Set Constraints", None))
        self.actionFind_Route.setText(QCoreApplication.translate("MainWindow", u"Find Route", None))
        self.new_network_button.setText(QCoreApplication.translate("MainWindow", u"New Network", None))
        self.save_network_button.setText(QCoreApplication.translate("MainWindow", u"Save Network", None))
        self.add_router_button.setText(QCoreApplication.translate("MainWindow", u"Add Router", None))
        self.edit_router_button.setText(QCoreApplication.translate("MainWindow", u"Edit Router", None))
        self.load_network_button.setText(QCoreApplication.translate("MainWindow", u"Load Network", None))
        self.link_routers_button.setText(QCoreApplication.translate("MainWindow", u"Link Routers", None))
        self.delete_router_button.setText(QCoreApplication.translate("MainWindow", u"Delete Router", None))
        self.set_constraints_button.setText(QCoreApplication.translate("MainWindow", u"Set Constraints", None))
        self.find_route_button.setText(QCoreApplication.translate("MainWindow", u"Find Route", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuRouters.setTitle(QCoreApplication.translate("MainWindow", u"Routers", None))
        self.menuSolver.setTitle(QCoreApplication.translate("MainWindow", u"Solver", None))
    # retranslateUi