from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialog, QDialogButtonBox,
    QDoubleSpinBox, QLabel, QLineEdit, QSizePolicy,
    QSlider, QSpinBox, QWidget)

class UI_RouterCreator(object):
    def setupUi(self, router_creator):
        if not router_creator.objectName():
            router_creator.setObjectName(u"router_creator")
        router_creator.resize(640, 380)
        self.buttonBox = QDialogButtonBox(router_creator)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(10, 340, 621, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.label = QLabel(router_creator)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(4, 5, 631, 61))
        self.label_2 = QLabel(router_creator)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 90, 141, 31))
        self.name_input = QLineEdit(router_creator)
        self.name_input.setObjectName(u"name_input")
        self.name_input.setMaxLength(128)
        self.name_input.setGeometry(QRect(110, 130, 511, 31))
        self.id_input = QSpinBox(router_creator)
        self.id_input.setObjectName(u"id_input")
        self.id_input.setGeometry(QRect(70, 90, 551, 31))
        self.id_input.setMaximum(99999)
        self.id_input.setValue(1)
        self.x_input = QDoubleSpinBox(router_creator)
        self.x_input.setObjectName(u"x_input")
        self.x_input.setMinimum(-2.0)
        self.x_input.setMaximum(21.0)
        self.x_input.setGeometry(QRect(160, 170, 461, 31))
        self.y_input = QDoubleSpinBox(router_creator)
        self.y_input.setObjectName(u"y_input")
        self.y_input.setMinimum(-1.0)
        self.y_input.setMaximum(12.0)
        self.y_input.setGeometry(QRect(160, 210, 461, 31))
        self.security_input = QSpinBox(router_creator)
        self.security_input.setObjectName(u"security_input")
        self.security_input.setGeometry(QRect(210, 250, 411, 31))
        self.security_input.setMinimum(1)
        self.security_input.setMaximum(5)
        self.firewall_input = QSlider(router_creator)
        self.firewall_input.setObjectName(u"firewall_input")
        self.firewall_input.setGeometry(QRect(199, 290, 351, 31))
        self.firewall_input.setMaximum(1)
        self.firewall_input.setOrientation(Qt.Horizontal)
        self.label_3 = QLabel(router_creator)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(560, 290, 61, 31))
        self.label_4 = QLabel(router_creator)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(130, 290, 61, 31))
        self.label_5 = QLabel(router_creator)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 130, 141, 31))
        self.label_6 = QLabel(router_creator)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 170, 141, 31))
        self.label_7 = QLabel(router_creator)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 210, 141, 31))
        self.label_8 = QLabel(router_creator)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 250, 181, 31))
        self.label_9 = QLabel(router_creator)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 290, 141, 31))
        self.error_label = QLabel(router_creator)
        self.error_label.setObjectName(u"error_label")
        self.error_label.setGeometry(QRect(10, 340, 421, 31))

        self.retranslateUi(router_creator)
        self.buttonBox.accepted.connect(router_creator.accept)
        self.buttonBox.rejected.connect(router_creator.reject)

        QMetaObject.connectSlotsByName(router_creator)
    # setupUi

    def retranslateUi(self, router_creator):
        router_creator.setWindowTitle(QCoreApplication.translate("router_creator", u"Router Creator", None))
        self.label.setText(QCoreApplication.translate("router_creator", u"<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">Router Creator</span></p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("router_creator", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">ID :</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("router_creator", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Enabled</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("router_creator", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Disabled</span></p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("router_creator", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Name :</span></p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("router_creator", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">X Position :</span></p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("router_creator", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Y Position :</span></p></body></html>", None))
        self.label_8.setText(QCoreApplication.translate("router_creator", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Security Level :</span></p></body></html>", None))
        self.label_9.setText(QCoreApplication.translate("router_creator", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Firewall :</span></p></body></html>", None))
        self.error_label.setText("")
    # retranslateUi